export const PRODUCTS = [
  {
    id: 0,
    agree: "cash",
    exchange: "NSE",
    stock: "IBM",
    quantity: 1,
    orderType: "Market",
    limitPrice: 350,
  },
  {
    id: 1,
    agree: "cash",
    exchange: "NSE",
    stock: "AMZN",
    quantity: 35,
    orderType: "Market",
    limitPrice: 200,
  },
  {
    id: 2,
    agree: "cash",
    exchange: "NSE",
    stock: "MSFT",
    quantity: 25,
    orderType: "Market",
    limitPrice: 790,
  },
  {
    id: 3,
    agree: "cash",
    exchange: "NSE",
    stock: "GOOG",
    quantity: 15,
    orderType: "Market",
    limitPrice: 690,
  },
  {
    id: 4,
    agree: "cash",
    exchange: "NSE",
    stock: "AAPL",
    quantity: 10,
    orderType: "Market",
    limitPrice: 3000,
  },
];
